### ISSUE TITLE
TypeError: nodecg.declareSyncedVar is not a function

### ISSUE THREAD

**Issue by Kanthos** [TamMcDonald/nodecg-transition#11]
I have no idea what I'm doing so I'm learning as I go. I've managed to get a ton of bundles working and taking a peek at them so far but I keep getting this error from the transition bundle every time I try to run nodecg. Please help!

**Comment by Tam** [comment]
I haven't updated this bundle in a while, and that function is no longer used in NodeCG (replaced by Replicants). I'm working on updating them at the moment, but probably won't have a working version released for a week or so!

**Comment by Kanthos** [comment]
That makes sense! I'll just wait for an update then. That'll give me time to start working on the transition graphics. Thanks for the reply!
