### ISSUE TITLE
What URL to use 

### ISSUE THREAD

**Issue by samek104** [TamMcDonald/nodecg-transition#4]
The default URL for OBS Remote in the config file is "localhost", and given that the URL the service now uses is http://client.obsremote.com, the aformentioned does not work anymore.

What is to be added in the config file itself (as the waiting for OBS timeouts in NodeCG Dashboard) in order for it to work?

Thank you for your contribution.

**Comment by Tamfoolery** [comment]
http://client.obsremote.com is OBS Remote's official GUI client, what the config file needs is the address of OBS itself (the remote client uses this as well if you click on the red or green dot in the bottom left).

Basically this means you can use NodeCG & Transition on a separate computer on the local network.

If you have NodeCG running on the same computer as OBS, and you haven't changed any of the default configs of the OBS Remote plugin is should work out of the box.
